name: budget_managing
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  path: ^1.9.1
  sqflite: ^2.4.2
  intl: ^0.18.1
  fl_chart: ^0.70.2
  file_saver: ^0.2.14
  printing: ^5.10.3
  pdf: ^3.10.4
  google_fonts: ^4.0.4
  provider: ^6.0.5
  shared_preferences: ^2.5.3
  google_generative_ai: ^0.4.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
